Repository DevExpress/devextreme-react, pull requests merged in 2023-08, with the labels that each got.

#857 Fix GitHub CI test run.
  .github/workflows/tests.yml
Labels: 23_2

#858 Fix GitHub CI test run. (#857)
  .github/workflows/tests.yml
Labels: cherry-pick, 23_1

#859 CI: make generator buildable locally
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/tsconfig.local.json
Labels: 23_2

#861 Fix Options type generation
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/component-generator.test.ts
  packages/devextreme-react-generator/src/component-generator.ts
Labels: 23_2

#863 CI: bump generator version
  packages/devextreme-react-generator/package.json
Labels: 23_2

#865 Support multiple ReturnValueTypes for func props
  package-lock.json
  package.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/generator.test.ts
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/package.json
Labels: bug, 23_2
