Repository DevExpress/devextreme-react, pull requests merged in 2023-06, with the labels that each got.

#839 Fallback from Record<string, any> to 'any' for function parameters
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/package.json
Labels: bug, 23_1

#842 Chore/update version 23 2
  .github/workflows/tests.yml
  lerna.json
  package-lock.json
  package.json
  packages/devextreme-react-generator/package-lock.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react/package-lock.json
  packages/devextreme-react/package.json
  packages/devextreme-react/src/core/__tests__/config.test.tsx
  packages/devextreme-react/src/core/__tests__/template.test.tsx
  packages/devextreme-react/src/core/dx-template.ts
  packages/sandbox/package.json
Labels: 23_2

#844 chore: update CI scripts
  .github/workflows/tests.yml
  lerna.json
  package-lock.json
  package.json
  packages/devextreme-react-generator/package-lock.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react/package-lock.json
  packages/devextreme-react/package.json
  packages/devextreme-react/src/core/__tests__/config.test.tsx
  packages/devextreme-react/src/core/__tests__/template.test.tsx
  packages/devextreme-react/src/core/dx-template.ts
  packages/sandbox/package.json
Labels: cherry-pick, 23_1

#847 hotfix: update devextreme-internal-tools to beta.17
  package-lock.json
  package.json
Labels: 23_2

#849 hotfix: devextreme-internal-tools to beta.17
  package-lock.json
  package.json
Labels: cherry-pick, 23_1
