Repository DevExpress/devextreme-react, pull requests merged in 2023-03, with the labels that each got.

#812 CI: update actions, setup dotnet 3.1
  .github/workflows/tests.yml
Labels: 22_1

#814 Generate types for config-components props
  packages/devextreme-react-generator/src/generator.test.ts
  packages/devextreme-react-generator/src/generator.ts
Labels: enhancement, 23_1

#815 Bump generator version to 3.0.0
  packages/devextreme-react-generator/package-lock.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react/package.json
Labels: 23_1

#809 Generate reexports in components
  package-lock.json
  package.json
  packages/devextreme-react-generator/package-lock.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/component-generator.ts
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/package.json
Labels: enhancement
