Repository DevExpress/devextreme-react, pull requests merged in 2023-02, with the labels that each got.

#806 Fix chart axis and annotation render (T1124149)
  .github/workflows/tests.yml
  packages/devextreme-react/src/core/__tests__/template.test.tsx
  packages/devextreme-react/src/core/templates-renderer.tsx
Labels: cherry-pick, 22_2

#808 Remove deprecated ui folder rendering
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/component-generator.ts
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/build.config.js
  packages/devextreme-react/gulpfile.js
Labels: enhancement

#810 Revert deprecated folder removing
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/component-generator.ts
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/build.config.js
  packages/devextreme-react/gulpfile.js
Labels: bug

#807 Generate common modules reexports, remove deprecated ui folder rendering
  package.json
  packages/devextreme-react-generator/package.json
  packages/devextreme-react-generator/src/common-reexports-generator.ts
  packages/devextreme-react-generator/src/component-generator.ts
  packages/devextreme-react-generator/src/generator.ts
  packages/devextreme-react/build.config.js
  packages/devextreme-react/gulpfile.js
  packages/devextreme-react/package.json
Labels: enhancement
